# Generated by Django 5.2.17 on 2026-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='File ka name ya label', max_length=200)),
                ('file', models.FileField(upload_to='anexa_assets/')),
                ('file_url', models.URLField(blank=True, max_length=1000)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
