# Generated by Django 5.2.17 on 2026-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_uploadedasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedasset',
            name='file_type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='uploadedasset',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
